function calibrated_parameter_fao_irrigated()
    p = (;
        α_com_height = (truncated(Normal(0.0, 0.5); lower = 0.0, upper = 3.0),
                        as(Real, 0.0, 3.0),
                        """TODO"""),
        γ₁ = (truncated(Normal(50000, 1000); lower = 40000, upper = 60000),
                        as(Real, 0.0, 2.0),
                        """TODO"""),
        γ₂ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
                        as(Real, 0.0, 2.0),
                        """TODO"""),
        T₀ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
                        as(Real, 0.0, 2.0),
                        """TODO"""),
        T₁ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
              as(Real, 0.0, 2.0),
              """TODO"""),
        T₂ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
              as(Real, 0.0, 2.0),
              """TODO"""),
        T₃ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
              as(Real, 0.0, 2.0),
              """TODO"""),
        ST₁ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
               as(Real, 0.0, 2.0),
               """TODO"""),
        ST₂ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
               as(Real, 0.0, 2.0),
               """TODO"""),
        SEA_min = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
                   as(Real, 0.0, 2.0),
                   """TODO"""),
        SEA_max = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
                   as(Real, 0.0, 2.0),
                   """TODO"""),
        α_sen = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
                 as(Real, 0.0, 2.0),
                 """TODO"""),
        Ψ₁ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
              as(Real, 0.0, 2.0),
              """TODO"""),
        Ψ₂ = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
              as(Real, 0.0, 2.0),
              """TODO"""),
        SEN_max = (truncated(Normal(0.0, 0.05); lower = 0.0, upper = 2.0),
                   as(Real, 0.0, 2.0),
                   """TODO"""))

    prepare_calibration_obj(; p)
end
