[Hainich_BE_three_sites]
git-tree-sha1 = "963c42adf97b4a1defa28582decb196bfd312209"

    [[Hainich_BE_three_sites.download]]
    sha256 = "708e551622b062901c2a12a4d685510837db2c2ff9c50355a84ab46ca3f1a8ba"
    url = "https://github.com/FelixNoessler/grassland-data/raw/refs/heads/master/Hainich_BE_three_sites.tar.gz"
