include("dashboard/dashboard.jl")
include("dashboard/dashbaord_layout.jl")
include("dashboard/dashboard_plotting.jl")
include("dashboard/dashboard_prepare_input.jl")
include("dashboard/gradient.jl")

include("doc_figures/doc_figures_utils.jl")
include("doc_figures/clonalgrowth.jl")
include("doc_figures/functional_response.jl")
include("doc_figures/potential_growth.jl")
include("doc_figures/landuse.jl")
include("doc_figures/reducer_functions.jl")
include("doc_figures/height_influence.jl")
include("doc_figures/plant_available_water.jl")
include("doc_figures/leaflifespan.jl")
